apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: melidob/user-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              value: "postgres://user:password@postgres:5432/users"
